---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomwebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecomwebsite
  template:
    metadata:
      labels:
        app: ecomwebsite
    spec:
      containers:
      - name: ecomwebsite
        image: chndra/ecommercewebsite:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: ecomwebsite-service
spec:
  selector:
    app: ecomwebsite
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
